www:
  #build: www
  image: toeknee/trainingwheels
  expose:
    - "5000"
  links:
    - redis
  user: nobody
  mem_limit: 200000000

redis:
  image: redis
  mem_limit: 50000000

lb:
  image: tutum/haproxy
  links:
   - www
  ports:
   - "80:80"
  environment:
   - BACKEND_PORT=5000
   - BALANCE=roundrobin
