etcd:
  image: gcr.io/google_containers/etcd:2.0.12
  net: host
  command: ['/usr/local/bin/etcd', '--bind-addr=0.0.0.0:4001', '--data-dir=/var/etcd/data']

scheduler:
  image: gcr.io/google_containers/hyperkube:v1.0.1
  net: host
  command: ["/hyperkube", "scheduler", "--master=127.0.0.1:8080", "--v=2"]

kubelet:
  image: gcr.io/google_containers/hyperkube:v1.0.1
  net: host
  pid: host
  privileged: true
  command: ['/hyperkube', 'kubelet', '--containerized', '--hostname-override=127.0.0.1', '--address=0.0.0.0', '--api-servers=http://localhost:8080', '--config=/etc/kubernetes/manifests']
  volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /dev:/dev
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw

proxy:
  image: gcr.io/google_containers/hyperkube:v1.0.1
  net: host
  privileged: true
  command: ['/hyperkube', 'proxy', '--master=http://127.0.0.1:8080', '--v=2']
