apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: trainingwheels
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: trainingwheels
    tier: frontend
