apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: trainingwheels
    tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: trainingwheels
  #   tier: frontend
  template:
    metadata:
      labels:
        app: trainingwheels
        tier: frontend
    spec:
      containers:
      - name: trainingwheels
        image: toeknee/trainingwheels
        env:
        - name: GET_HOSTS_FROM
          value: env
    #    - name: "PUBLIC_REDIS_PORT"
    #      value: "EXPOSED_PORT"
        ports:
        - containerPort: 5000
