apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    app: trainingwheels
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: trainingwheels
        tier: frontend
    spec:
      containers:
      - name: trainingwheels
        image: toeknee/trainingwheels
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 5000
